# Generated by Django 4.0.4 on 2022-05-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0007_remove_subject_activities'),
        ('AppActivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attempts',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='gradeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_grade',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCourse.subject'),
        ),
        migrations.AddField(
            model_name='activity',
            name='timeclose',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='timed_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='timed_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='timelimit',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='timeopen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
