# Generated by Django 4.0.4 on 2022-05-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0008_alter_course_timecreated_alter_course_timemodified_and_more'),
        ('AppActivity', '0002_activity_attempts_activity_gradeable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigment',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppActivity.activity')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
            bases=('AppActivity.activity',),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='')),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('timemodified', models.DateTimeField(auto_now=True, null=True)),
                ('resource_type', models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'File'), (2, 'Folder')], default=0)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='gradeable',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_grade',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='timed_attempt',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='timelimit',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Quiz'), (2, 'Assigment'), (3, 'Forum'), (4, 'Lesson')], default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='timecreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='timemodified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppActivity.resource')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
            bases=('AppActivity.resource',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppActivity.activity')),
                ('gradeable', models.BooleanField(default=False)),
                ('timed_attempt', models.BooleanField(default=False)),
                ('timelimit', models.BigIntegerField(blank=True, default=0, null=True)),
                ('attempts', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('grademethod_type', models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Automatic'), (2, 'Direct'), (3, 'Rubric'), (4, 'Marking'), (9, 'Mixed')], default=0)),
                ('decimalpoints', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('questiondecimalpoints', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('shuffleanswers', models.BooleanField(blank=True, default=False, null=True)),
                ('max_grade', models.FloatField(blank=True, default=7.0, null=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
            bases=('AppActivity.activity',),
        ),
        migrations.AddField(
            model_name='resource',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppActivity.activity'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCourse.subject'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppActivity.resource')),
                ('file', models.FileField(upload_to='archives/')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppActivity.folder')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
            },
            bases=('AppActivity.resource',),
        ),
    ]
