# Generated by Django 4.0.4 on 2022-06-01 14:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('AppUser', '0001_initial'), ('AppUser', '0002_annotation_enrollmentsubject_enrollmentcourse'), ('AppUser', '0003_annotation_timecreated_annotation_timemodified_and_more'), ('AppUser', '0004_alter_customuser_address_alter_customuser_birthdate_and_more'), ('AppUser', '0005_alter_customuser_address_alter_customuser_birthdate_and_more'), ('AppUser', '0006_alter_customuser_user_type')]

    initial = True

    dependencies = [
        ('AppCourse', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('deleted', models.BooleanField(default=False, verbose_name='Borrado')),
                ('suspended', models.BooleanField(default=False, verbose_name='Suspendido')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Usuario')),
                ('firstname', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre')),
                ('lastname', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='Email')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Cumpleaños')),
                ('phonel', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Celular')),
                ('phone2', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefono')),
                ('institution', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Institucion')),
                ('department', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Departamento')),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Ciudad')),
                ('firstlogin', models.DateTimeField(blank=True, null=True, verbose_name='Primera Conexion')),
                ('lastlogin', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Conexion')),
                ('lastip', models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Ultima IP')),
                ('picture', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Imagen')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripcion')),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('timemodified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('imagealt', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Imagen Alternativa')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SuperUsuario')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Conexion2')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Student'), (2, 'Teacher'), (3, 'Parent'), (4, 'Admin')], default=1, verbose_name='Tipo de Usuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tittles', models.TextField()),
                ('experience', models.TextField()),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
            bases=('AppUser.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alumnos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customUser_alumnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
            bases=('AppUser.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='customUser_taker', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCourse.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUser_giver', to='AppUser.teacher')),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('timemodified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Anotacion',
                'verbose_name_plural': 'Anotaciones',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCourse.course')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('timemodified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Cursando Curso',
                'verbose_name_plural': 'Cursando Cursos',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCourse.subject')),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('timemodified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Cursando Materia',
                'verbose_name_plural': 'Cursando Materias',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
