# Generated by Django 4.0.4 on 2022-05-13 20:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('deleted', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phonel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('institution', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('firstlogin', models.DateTimeField(blank=True, null=True)),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
                ('lastip', models.CharField(blank=True, default='', max_length=45, null=True)),
                ('picture', models.BigIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
                ('timemodified', models.DateTimeField(auto_now=True)),
                ('imagealt', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'parent'), (4, 'admin')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tittles', models.TextField()),
                ('experience', models.TextField()),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
            bases=('AppUser.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alumnos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customUser_alumnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
            bases=('AppUser.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
