# Generated by Django 4.0.4 on 2022-05-16 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0001_initial'),
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='customUser_taker', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCourse.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUser_giver', to='AppUser.teacher')),
            ],
            options={
                'verbose_name': 'Anotacion',
                'verbose_name_plural': 'Anotaciones',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCourse.subject')),
            ],
            options={
                'verbose_name': 'Cursando Materia',
                'verbose_name_plural': 'Cursando Materias',
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='EnrollmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCourse.course')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cursando Curso',
                'verbose_name_plural': 'Cursando Cursos',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
