# Generated by Django 4.0.4 on 2022-05-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0003_annotation_timecreated_annotation_timemodified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Dirección', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Cumpleaños', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Ciudad', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Borrado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Departamento', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripcion', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstlogin',
            field=models.DateTimeField(blank=True, help_text='Primera Conexion', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, default='', help_text='Nombre', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imagealt',
            field=models.CharField(blank=True, default='', help_text='Imagen Alternativa', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution',
            field=models.CharField(blank=True, default='', help_text='Institucion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Activo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='SuperUsuario'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Ultima Conexion2', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastip',
            field=models.CharField(blank=True, default='', help_text='Ultima IP', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastlogin',
            field=models.DateTimeField(blank=True, help_text='Ultima Conexion', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(blank=True, default='', help_text='Apellido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone2',
            field=models.CharField(blank=True, default='', help_text='Telefono', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonel',
            field=models.CharField(blank=True, default='', help_text='Celular', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.BigIntegerField(blank=True, default=0, help_text='Imagen', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='suspended',
            field=models.BooleanField(default=False, help_text='Suspendido'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='timecreated',
            field=models.DateTimeField(auto_now_add=True, help_text='Creado', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='timemodified',
            field=models.DateTimeField(auto_now=True, help_text='Modificado', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'parent'), (4, 'admin')], default=1, help_text='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Usuario', max_length=150, unique=True),
        ),
    ]
