# Generated by Django 4.0.4 on 2022-05-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0004_alter_customuser_address_alter_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Cumpleaños'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstlogin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primera Conexion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imagealt',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Imagen Alternativa'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Institucion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='SuperUsuario'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima Conexion2'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastip',
            field=models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='Ultima IP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastlogin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima Conexion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonel',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='suspended',
            field=models.BooleanField(default=False, verbose_name='Suspendido'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='timecreated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='timemodified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Usuario'),
        ),
    ]
