# Generated by Django 4.0.4 on 2022-05-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0005_alter_customuser_address_alter_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Student'), (2, 'Teacher'), (3, 'Parent'), (4, 'Admin')], default=1, verbose_name='Tipo de Usuario'),
        ),
    ]
