# Generated by Django 4.0.4 on 2022-06-01 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('AppCourse', '0001_initial'), ('AppCourse', '0002_subject_course'), ('AppCourse', '0003_subject_activities'), ('AppCourse', '0004_alter_subject_activities'), ('AppCourse', '0005_alter_course_level'), ('AppCourse', '0006_alter_course_enddate_alter_course_shortname_and_more'), ('AppCourse', '0007_remove_subject_activities'), ('AppCourse', '0008_alter_course_timecreated_alter_course_timemodified_and_more'), ('AppCourse', '0009_section_correlative_alter_section_course_and_more'), ('AppCourse', '0010_alter_course_enddate_alter_course_startdate_and_more'), ('AppCourse', '0011_alter_course_grade'), ('AppCourse', '0012_alter_course_enddate_alter_course_fullname_and_more'), ('AppCourse', '0013_course_year_alter_course_grade'), ('AppCourse', '0014_remove_course_fullname_remove_course_shortname'), ('AppCourse', '0015_remove_course_enddate_remove_course_startdate'), ('AppCourse', '0016_subject_auto_enroll_alter_subject_course_and_more')]

    initial = True

    dependencies = [
        ('AppActivity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('visible', models.BooleanField(default=True, verbose_name='Visibilidad')),
                ('timecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('timemodified', models.DateTimeField(auto_now=True, null=True)),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuardo'), (5, 'Quinto'), (6, 'Sexto'), (7, 'Séptimo'), (8, 'Octavo')], default=0, verbose_name='Grado')),
                ('grade_letter', models.CharField(default='', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only capitalized alpha characters are allowed.')], verbose_name='Letra')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Básico'), (2, 'Medio')], default=0, verbose_name='Tipo de Usuario')),
                ('year', models.PositiveIntegerField(default=2022, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)], verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripccion')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCourse.course', verbose_name='Curso')),
                ('auto_enroll', models.BooleanField(default=True, verbose_name='Matricula Automatica')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField(default='')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCourse.subject')),
                ('correlative', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
    ]
