# Generated by Django 4.0.4 on 2022-06-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0001_squashed_0016_subject_auto_enroll_alter_subject_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='course',
            new_name='subject',
        ),
    ]
