# Generated by Django 4.0.4 on 2022-05-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCourse.course'),
        ),
    ]
