# Generated by Django 4.0.4 on 2022-06-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0002_rename_course_section_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('grade', 'grade_letter', 'level', 'year')},
        ),
    ]
