# Generated by Django 4.0.4 on 2022-06-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_squashed_0006_alter_customuser_user_type'),
        ('AppCourse', '0003_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_teacher',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUser.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUser.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Básico'), (2, 'Medio')], default=0, verbose_name='Nivel'),
        ),
    ]
