# Generated by Django 4.0.4 on 2022-05-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0004_alter_subject_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Básico'), (2, 'Medio')], default=0),
        ),
    ]
