# Generated by Django 4.0.4 on 2022-06-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_squashed_0006_alter_customuser_user_type'),
        ('AppCourse', '0004_course_class_teacher_subject_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUser.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUser.teacher'),
        ),
    ]
