# Generated by Django 4.0.4 on 2022-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0010_alter_course_enddate_alter_course_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, '1'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=0),
        ),
    ]
