# Generated by Django 4.0.4 on 2022-05-31 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0011_alter_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Termino'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fullname',
            field=models.CharField(max_length=254, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuardo'), (5, 'Quinto'), (6, 'Sexto'), (7, 'Séptimo'), (8, 'Octavo')], default=0, verbose_name=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade_letter',
            field=models.CharField(default='', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only capitalized alpha characters are allowed.')], verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Básico'), (2, 'Medio')], default=0, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='course',
            name='shortname',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre Corto'),
        ),
        migrations.AlterField(
            model_name='course',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visibilidad'),
        ),
    ]
