# Generated by Django 4.0.4 on 2022-05-31 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0012_alter_course_enddate_alter_course_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.PositiveIntegerField(default=2022, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Custom'), (1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuardo'), (5, 'Quinto'), (6, 'Sexto'), (7, 'Séptimo'), (8, 'Octavo')], default=0, verbose_name='Grado'),
        ),
    ]
