# Generated by Django 4.0.4 on 2022-06-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0014_remove_course_fullname_remove_course_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='startdate',
        ),
    ]
