# Generated by Django 4.0.4 on 2022-06-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCourse', '0015_remove_course_enddate_remove_course_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='auto_enroll',
            field=models.BooleanField(default=True, verbose_name='Matricula Automatica'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCourse.course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripccion'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Titulo'),
        ),
    ]
